DISPAK          = dispak --input-encoding=utf8

all:            assembler.txt loader.txt test.txt

assembler.txt:  assembler.b6
		$(DISPAK) $< > $@

loader.txt:     loader.b6
		$(DISPAK) $< > $@

test.txt:       test.b6
		$(DISPAK) $< > $@
