*NAME OC-9 (errmacro - server)
*TIME:24.00
*EXPRESS
*PAGE:999,LIST
*LIBRA:23
*DISC:705/SYSTEM,LCROSS
*FILE:LIB,67
*FILE:MEM,30,W
*PERSO:67
*TAKE TAPE:67
*          *DISC:705/SYSTEM,WORKIN
*          *FILE:LCROSS     - PERSO ACCEMБЛEP+ЗAГPYЗЧИK+ЭMYЛЯTOP
*          *FILE:ASSEM      - OПИCAHИE И TEKCTЫ ACCEMБЛEPA И ЗAГPYЗЧИKA
*          *FILE:EXMEM      - ПAMЯTЬ ДЛЯ MOДYЛEЙ ЗAГPYЗKИ
*          *FILE:EML        - TEKCTЫ ЭMYЛЯTOPA (ЗOHA=1)
*          *FILE:OS         - MAKPOCЫ ( 0 )  И TEKCTЫ  O C  ( 120 )
*CALL FICMEMOR
*NO LIST
*CALL ZMACRO
ERRMACRO:NAME QF
;*
;*********************************************
;*                                           *
;*      СТАНДАРТНАЯ ОБРАБОТКА СОБЫТИЙ.       *
;*      ПEЧATЬ COOБЩEHИЯ OБ OШИБKE ИЛИ       *
;*      KOHЦE ЗAДAЧИ, A TAKЖE PEГИCTPOB      *
;*                                           *
;*********************************************
;*
;*     TEKYЩEE COCTOЯHИE ЗAДAЧИ HAXOДИTCЯ
;*     B BEPШИHE CTEKA YПPЯTЫBAHИЯ :
;*       0 :       И1          И2
;*       7 :       И15         И16
;*       8 :       CЧAC        POП
;*       9 :       PP          PPP
;*      10 :          CYMMATOP
;*      11 :           P M P
;*     KPOME TOГO, B "INFERR" ПEPEДAЮTCЯ :
;*                 ИAOП     HOM.OШ. ИЛИ 0
;*
;*     НОМЕР СОБЫТИЯ - В РЕГИСТРЕ  IA
;*
ENDJOB:SUBP QF
TERMOS:SUBP QF
DHEX8:SUBP QF
F_WRIT:SUBP QF
TIME:SUBP QF
FATA
IFP
VMD
EVENT
OUTFIL:EQU 3 ; ФAЙЛ-ЛИCTИHГ
LLIST:EQU BFPOOL+OUTFIL<<10
CODE
MODIF
U:EQU P1
;
CONST
;
THD:CHAR "M1-M8:  M9-16:  CM,MP:  "
TKILL:CHARZ "ЗАДАЧА СНЯТА.'13''10'"
;  0
TERROR:CHARZ "KOHEЦ ЗAДAЧИ.'13''10'"
:CHARZ "OTC.БЛOK ПAMЯTИ'13''10'"
:CHARZ "MHOГOKP.OШИБKA'13''10'"
:CHARZ "TIME-OUT OЗY'13''10'"
:CHARZ "TIME-OUT ШИHЫ'13''10'"
:CHARZ "OШ.ПPOГ.ПPEP.'13''10'"
:CHARZ "ЗAПP.KOM. ИЛИ ПЛOXOЙ ЭKCTPAKOД.'13''10'"
:CHARZ "OTC.AДPEC ПAMЯTИ'13''10'"
:CHARZ "OTPИЦ.HOMEP CTPAHИЦЫ Y KOMAHДЫ'13''10'"
:CHARZ "OTPИЦ.HOMEP CTPAHИЦЫ Y OПEPAHДA'13''10'"
;  10
:CHARZ "ПPOГP.ИHTEPП.TEГA KOMAHДЫ'13''10'"
:CHARZ "ПPOГP.ИHTEPП.TEГA OПEPAHДA'13''10'"
:CHARZ "ЗAЩИTA AДPECA ПPИ ЧTEHИИ'13''10'"
:CHARZ "KOHTPOЛЬ KOMAHДЫ'13''10'"
:CHARZ "???"
:CHARZ "OПEPAHД B ЧYЖOM ЛИCTE'13''10'"
:CHARZ "KOMAHДA B ЧYЖOM ЛИCTE'13''10'"
:CHARZ "ЗAЩИTA CTPAHИЦЫ ПO OБPAЩEHИЮ'13''10'"
:CHARZ "ЗAЩИTA CTPAHИЦЫ ПO ЗAПИCИ'13''10'"
:CHARZ "ЗAЩИTA BЫБOPKИ KOMAHДЫ'13''10'"
;  20
:CHARZ "ЗAЩИTA ПEPEДAЧИ YПPABЛEHИЯ'13''10'"
:CHARZ "ЗAЩИTA AДPECA ПPИ ЗAПИCИ'13''10'"
:CHARZ "ЧYЖOЙ CYMMATOP'13''10'"
:CHARZ "ЧYЖOЙ OПEPAHД'13''10'"
:CHARZ "???"
:CHARZ "???"
:CHARZ "???"
:CHARZ "???"
:CHARZ "???"
:CHARZ "ШAГOBЫЙ PEЖИM'13''10'"
;  30
:CHARZ "???"
:CHARZ "???"
:CHARZ "???"
:CHARZ "ПEPEПOЛHEHИE'13''10'"
:CHARZ "ПEPEПOЛHEHИE ПOPЯДKA БЭCM-6'13''10'"
:CHARZ "ДEЛEHИE HA 0'13''10'"
:CHARZ "ПППYПP"
:CHARZ "HEЗAKOHHЫЙ OПEPAHД'13''10'"
:CHARZ "0-Й MAT.AДPEC'13''10'"
:CHARZ "???"
;  40
:CHARZ "Запись в файл запрещена!'13''10'"
:CHARZ "Лишняя команда RETS !!!'13''10'"
:CHARZ "Нет массива для ввода'13''10'"
;
CMD
;
;MOZY=81219      ;   - ERRMACRO
;
KTOЯ
ATI TN
ГHOM
ATI NG
CMON БBП
SETR БЧOП+БЧC
WTC ASTEC
P2 VTM -16
XTA INFERR
P2 ATX 12
ATI J
ASFT 32
ATI PA ; ИAOП
U VTM OUTFIL
U XTA FDB
AAU @1FFF ; HAЧ.AДPEC
RI VTMB LLIST ;  ПO
A+I RI ; БYФEPY
ATI RI ; ЛИCTИHГA
IA JMP SW_EVEN-1
;
SW_EVEN:I VTM TERROR
JMP ST1
:HLT @222
:HLT @333
:HLT @444
:HLT @555
:I VTM TKILL
JMP ST2
;
ST1:J JMEQ ST2
I XTA
I UTM 1
AAU @FF
JANE ST1
J VRM ST1
ST2:
RR VJM STROUT
;
P2 MSFT -1
I VTMB BUF+2
XTA ="   CЧAC:"
JMPS FRAG6
P2 HTA 16
ATI CP
JMPS DIG5
XTA ="   ИAOП:"
JMPS FRAG6
ITA PA
JMPS DIG5
XTA ="    POП:"
JMPS FRAG6
P2 HTA 17
JMPS DIG5
XTA ="    PEЖ:"
JMPS FRAG6
P2 HTA 18
JMPS DIG8
UTA BL
I ATB
I UTM 1
P2 HTA 19
JMPS DIG8
XTA ="    Kom:"
JMPS FRAG6
CP TTA
ASFT 32
JMPS DIG8
UTA BL
I ATB
I UTM 1
CP TTA
JMPS DIG8
CP TTA
YTA
JMPS DHEX8
AAU @FFFF
AOX ="    T:'0''0'"
JMPS FRAG6
CP VTM -2
RR VJM STROUTB
;
REGOUT:CP XTA THD+2
ATX BUF+2
I VTMB BUF+2
CP JMNE *+2
P2 UTM 4
UTC 3-7
:RR VTM 7
I UTM 6
REG1:UTA BL ; ПPOБEЛ
I ATB
I UTM 1
P2 HTA
P2 UTM 1
JMPS DIG8
:RR VRM REG1
CP JMNE NEXLIN
XTA ="   СЧЕТ:"
JMPS FRAG6
:XTA IFCTIM
AEU -1
A/L =1000000
I MTJ CP
RR VJM TIME
CP MTJ I
CP VTM
W VTM 7
JMPS FRAG
;
NEXLIN:RR VJM STROUTB
CP VLM REGOUT
UTA ETX
RI ATB ; " E O F "
RI UTA 1
U AEX FDB
AAU @1FFF ; OФOPMЛEHИE
U AEX FDB ; KOHЦA ФAЙЛA
U ATX FDB ; C ЛИCTИHГOM
CLRR БЧOП+БЧC
JMP ENDJOB
;
FRAG6:W VTM 5
JMP FRAG
DIG8:UTC 7-4
DIG5:W VTM 4
JMPS DHEX8
FRAG:I MTJ J
W J+M J
FR1:J ATB
ASFT 8
J UTM -1
I UTM 1
W VRM FR1
RETS
;
STROUTB:UTA CR
I ATB
UTA LF
I ATB 1
UTA
I ATB 2
I VTM BUF+2
STROUT:I MTJ J
J MSFT -3
UTA BL
JMP TRLST1
;
TRLST:J BTA
J UTM 1
TRLST1:RI ATB
JAEQ STROUTT
RI UTM 1
ITA RI
AAU @1FFF
JANE TRLST
NP VTM LLIST
U XTA FDB
ASFT 40
AAU @FF
RI VTMB LLIST
ATI W
JAEQ TRLST
W HTA FCOOR<<1
AON 64-46 ; 8K БAЙT
W VTM 0 ; MAIN TAG
RR MTJ R
RR VJM F_WRIT
R MTJ RR
JMP TRLST
STROUTT:J VTM 0
JMP TERMOS
END
SERVER:NAME QF
;*
;*******************************************
;*     ПOДБИPATEЛЬ ИЗ "ПOЧTOBOГO ЯЩИKA"    *
;*******************************************
;*
F_OPEN:SUBP QF
F_CREAT:SUBP QF
F_READ:SUBP QF
F_WRIT:SUBP QF
TERMOS:SUBP QF
ENDJOB:SUBP QF
DHEX8:SUBP QF
;
IFP
MODIF
U:EQU P1
MEM:EQU 41<<10 ; PAБ.ПAMЯTЬ
;
;     ПPИ ЗAПYCKE REGSCAL COДEPЖИT KOД ДИPEKTИBЫ
;     ЗAПYCKA, PATHNAME - EE ПEPBЫЙ ПAPAMETP.
;     BCЯ CTPOKA OT ЗAПYCKA CИДИT B  BUF+2.
;     A ПOKA HAM HИЧEГO ЭTOГO HE HAДOБHO.
;
;MOZY=81655     ;   - SERVER
;
UTA
ATX REGSCAL
XTA ="D:\BESM6"
ATX PATHNAME
XTA ="\DIS667\"
ATX PATHNAME+1
XTA =Z"MD.MAD"
ATX PATHNAME+2
U VTM 63
;
XTA =Z"SERVER>"
ATX BUF+2
I VTM BUF+2
J VTM 1
RR VJM TERMOS+1
XTA BUF+2
AEU @47 ; "G"
AAU @FF
JANE ENDJOB
;
W VTM @84
RR VJM F_OPEN
JANE ABS_FILE
;
;       ЗACACЫBAEM BECЬ ФAЙЛ B ПAMЯTЬ
;
NP VTM MEM
W VTM ; MAIN TAG
NTA 64-46 ; 8KБAЙT
INPUT:15 ATX
RR VJM F_READ
U XTA FDB
ASFT 16
AAU @FFFF
AEU @2000
STI RR
A+U @2000
NP UTM @400 ; +1 ЛИCT
RR JMEQ INPUT
;
;      TИП (TEXT ИЛИ BIN) OПPEДEЛЯETCЯ ПO HAЛИЧИЮ
;      KOДA CMEЩEHИЯ B 16-17 БAЙTAX "MAIL BOX".
;
XTA MEM+2
ASFT 48
AEU @1200
JANE TEXT ; "TYPE"
ATX PATHNAME+2
I VTMB MEM
J VTMB PATHNAME+1
W VTM 5
;
;       ПEPEПИCЬ ЗAДAHHOГO ЧИCЛA БAЙT (C POTAЦИEЙ)
;       B ЗAДAHHЫЙ ФAЙЛ  (AHAЛOГ "BLOAD")
;
:I BTA 1
J ATB 1
I BTA
J ATB 2
I UTM 2
J UTM 2
W VRM *-3
;
NP VTM MEM
U VTM 62
R VJM F_CREAT
JAEQ ABS_FILE
;
I BTA 1
ASFT -8
I AOB
ASFT -8
I AOB 3
ASFT -8
I AOB 2
CALCLEN:ATI RI ; ДЛИHA ФAЙЛA
ASFT 1
ATI W ; K-BO ПAP БAЙTOB
W UTM -1
I UTM 6 ; OTKYДA
J VTMB MEM ; KYДA
:I BTA 1
J ATB
I BTA
J ATB 1
I UTM 2
J UTM 2
W VRM *-3
J VTM
I VTM =Z"BLOAD: "
RR VJM TERMOS+1
;
OUTPUT:RI MTJ I
RI UTM -8192
:RI JMLE *+1
I VTM 8192
:ITA I
ASFT -32
AOI J
RR VJM F_WRIT
J UTM 8192
NP UTM @400
RI JMGT OUTPUT
I UTC
J UTA -8192
J VTM =" БAЙT ЗAПИCAHO B"
MESS:15 MTJ I
JMPS DHEX8
:J XTS
J XTS 1
XTS =" ФAЙЛ   "
XTS PATHNAME+1
XTS PATHNAME+2
UTS
J VTM 0
RR VJM TERMOS+1
JMP ENDJOB
;
ABS_FILE:J VTM =" - HE OTKPЫЛCЯ"
JMP MESS
;
;
;       ПEPEПИCЬ TEKCTA (AHAЛOГ "TYPE")
;
TEXT:I VTM =Z" TYPE: "
J VTM 0
RR VJM TERMOS+1
HLT @23
END
*END F
